name: My workflow     # 工作流程的名称

on:
  push:
    branches:         # 选择要触发工作流程的分支
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest   # 运行的操作系统

    steps:
    - name: Checkout code    # checkout 代码库
      uses: actions/checkout@v2

    - name: Build project    # 构建项目
      run: |
        npm install        # 运行 npm 安装
        npm run build      # 运行构建脚本

    - name: Deploy to server  # 部署到服务器
      uses: easingthemes/deploy-ftp-action@v2
      with:
        ftp-server: $${{ secrets.FTP_SERVER }}   # 使用密钥保存 ftp 服务器信息
        ftp-username: $${{ secrets.FTP_USERNAME }}
        ftp-password: $${{ secrets.FTP_PASSWORD }}
        local-folder: "./dist/"          # 部署的本地目录
        server-folder: "/path/to/folder" # 部署到服务器的路径
